# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Academico/IPD432 Super Digitales/Proyectos Vivado 2017.3/project_3_HDMI_OUT/project_3_HDMI_OUT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
